[toolchain]
anchor_version = "0.31.1"
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
open_quanta = "5WzLQxJCSMZb5E4tTLHyzWFQY2UXGUaTqLN6S6kocjCV"

[programs.devnet]
open_quanta = "5WzLQxJCSMZb5E4tTLHyzWFQY2UXGUaTqLN6S6kocjCV"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
